apiVersion: v1
kind: Service
metadata:
  name: wingman-day1
  namespace: {{ include "wingman.namespace" . }}
  labels:
    {{- include "wingman.labels" . | nindent 4 }}
    app.kubernetes.io/component: day1
spec:
  selector:
    app.kubernetes.io/name: wingman
    app.kubernetes.io/component: day1
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: http
