apiVersion: apps/v1
kind: Deployment
metadata:
  name: wingman-nginx
  namespace: {{ include "wingman.namespace" . }}
  labels:
    {{- include "wingman.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  replicas: {{ .Values.replicaCount.nginx }}
  selector:
    matchLabels:
      app.kubernetes.io/name: wingman
      app.kubernetes.io/component: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wingman
        app.kubernetes.io/component: nginx
      annotations:
        checksum/nginx-config: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "wingman.serviceAccountName" . }}
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{- end }}
      containers:
        - name: nginx
          image: {{ include "wingman.image" (dict "reg" .Values.image.registry "repo" .Values.image.nginx.repository "tag" .Values.image.nginx.tag) }}
          imagePullPolicy: {{ .Values.image.nginx.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
          resources:
            {{- toYaml .Values.resources.nginx | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 15
      volumes:
        - name: nginx-config
          configMap:
            name: wingman-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: wingman-nginx
  namespace: {{ include "wingman.namespace" . }}
  labels:
    {{- include "wingman.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  selector:
    app.kubernetes.io/name: wingman
    app.kubernetes.io/component: nginx
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
